# Generated by Django 4.1.5 on 2023-03-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bookmarkQuestion',
            field=models.ManyToManyField(blank=True, related_name='bookmarkBy', to='parlio.question'),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlistQuestion',
            field=models.ManyToManyField(blank=True, related_name='watchlistBy', to='parlio.question'),
        ),
    ]
