# Generated by Django 4.1.5 on 2023-03-25 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlio', '0004_question_uin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='uin',
        ),
    ]
