# Generated by Django 4.1.5 on 2023-03-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlio', '0005_remove_question_uin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='uniqueId',
            field=models.IntegerField(unique=True),
        ),
    ]
